#!/bin/bash

# HOWTO
# generate github ssh keys first here:
# https://help.github.com/enterprise/2.12/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ 
# then run ./bootstrap

# TODO
# install vim
sudo apt install -y vim &&

# install curl
sudo apt install -y curl &&

# install git
sudo apt install -y git &&


# git config
git config --global user.email "gndowns@gmail.com" &&
git config --global user.name "Gabriel Downs" &&

# install vim-pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim &&

# clone vim plugins
PLUGINS=( "junegunn/fzf.vim" "mattn/emmet-vim" "morhetz/gruvbox"
 "scrooloose/nerdcommenter" "scrooloose/nerdtree" "tpope/vim-fugitive" )
for p in "${PLUGINS[@]}"; 
do
  URL="https://github.com/$p"
  REPO=`echo $p | cut -d '/' -f 2`
  git clone $URL ~/.vim/bundle/$REPO
done

# use .vimrc from dotfiles/
ln -s ~/dotfiles/.vimrc ~/.vimrc &&

# zsh && oh-my-zsh
sudo apt install -y zsh &&
chsh -s $(which zsh) &&
# edit terminal preferences after ~

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" &&

ln -s ~/dotfiles/.zshrc ~/.zshrc &&

# install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
~/.fzf/install &&

# install ag for fast search
sudo apt install -y silversearcher-ag &&

# ====tmux====
# cmake
sudo apt install -y cmake &&

# this seemed to fix the next step
sudo apt install -y libssl-dev &&

# libevent
sudo apt install -y libevent-dev &&

# ncurses
sudo apt install -y libncurses5-dev libncursesw5-dev &&

# this just fixed something
sudo apt install -y autotools-dev &&
sudo apt install -y automake &&

# tmux
git clone https://github.com/tmux/tmux.git ~/tmux && \
cd ~/tmux
sh autogen.sh &&
./configure && make &&
sudo make install &&

ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
