#!/bin/bash

# HOWTO
# generate github ssh keys first here:
# https://help.github.com/enterprise/2.12/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ 
# then run ./bootstrap (as root)


# ===== INSTALLS =====

# update dependency lists 
apt update

# install vim
apt install -y vim &&

# install curl
apt install -y curl &&

# install git
apt install -y git &&


# git config
git config --global user.email "gndowns@gmail.com" &&
git config --global user.name "Gabriel Downs" &&

# install vim-pathogen for plugins
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim &&

# clone vim plugins
PLUGINS=( "junegunn/fzf.vim" "mattn/emmet-vim" "morhetz/gruvbox"
 "scrooloose/nerdcommenter" "scrooloose/nerdtree" "tpope/vim-fugitive" )
for p in "${PLUGINS[@]}"; 
do
  URL="https://github.com/$p"
  REPO=`echo $p | cut -d '/' -f 2`
  git clone $URL ~/.vim/bundle/$REPO &&
done

# use .vimrc from dotfiles/
ln -s ~/dotfiles/.vimrc ~/.vimrc &&

# zsh && oh-my-zsh
apt install -y zsh &&
chsh -s $(which zsh) &&
# edit terminal preferences after ~

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" &&

ln -s ~/dotfiles/.zshrc ~/.zshrc &&

# install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
~/.fzf/install &&

# install ag for fast search
apt install -y silversearcher-ag &&

# GNU Screen
sudo apt install -y screen
